require.config({
    paths:{
        'jquery':'../lib/jquery-3.2.1',
        'carousel':'../lib/jquery-xcarousel/jquery.xCarousel',
        'scarousel':'../lib/jQuery.carousel/jQuery.scarousel',
        'common':'../js/common',
        'Zoom':'../lib/jquery.wgyZoom/jquery.wgyZoom',
        'autoCar':'../js/autoCar',
        'autoAjax':'../js/autoajax'
    },
    shim:{
        'carousel':['jquery'],
        'scarousel':['jquery'],
        'common':['jquery'],
        'Zoom':['jquery'],
        'autoCar':['jquery'],
        'autoAjax':['jquery']
    }
});